import type { Metadata } from "next";
import { Inter, Press_Start_2P, Geist } from "next/font/google";

import "./globals.css";
import { cn } from "@/lib/utils";
import { MouseGlow } from "@/components/mouse-glow";
import { Navbar } from "@/components/shared/navbar";
import { Footer } from "@/components/shared/footer";

const pressStart2P = Press_Start_2P({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-pixel",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "antialiased",
        pressStart2P.variable,
        "font-sans",
      )}
    >
      <body className="min-h-full flex flex-col">
        <MouseGlow />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
